### ISSUE TITLE
bad OEM

### ISSUE THREAD

**Issue by Sergei-Alekseev** [mirfatif/PermissionManagerX#10]
Alot of popups "Bad OEM".
But looks like app is working fine.
Android 8.1, MIUI 11, Redmi5+

**Comment by mirfatif** [comment]
You can ignore them. AppOps framework in MIUI returns unexpected results. The _Note_ in app description: _"The app is tested on stock Android 7-11. Some highly customized ROMs may behave unexpectedly."_
