### ISSUE TITLE
[Feature Request] Shizuku Support

### ISSUE THREAD

**Issue by ModdedGamers** [mirfatif/PermissionManagerX#13]
Could you add support for using [Shizuku](https://github.com/RikkaApps/Shizuku) as another way to enable Permission Manager X to work?

**Comment by mirfatif** [comment]
Not a bad idea but currently not on to-do list.

**Comment by mirfatif** [comment]
[Are you going to add Shizuku support to PMX?](https://mirfatif.github.io/PermissionManagerX/help/en/#faq30)
