### ISSUE TITLE
./build_set_priv.sh command 

### ISSUE THREAD

**Issue by rahulsaamanth** [mirfatif/PermissionManagerX#16]

**Comment by rahulsaamanth** [comment]
>  _No description provided._

createProcess error=193,1% is not a valid win32 applicstion

**Comment by mirfatif** [comment]
Building for F-Droid?
`build_set_priv.sh` was removed in https://github.com/mirfatif/PermissionManagerX/commit/8e1d5aff87b04b462a99c28731fd7e58bb7db3ed. Are you building at `v1.08`?
