### ISSUE TITLE
Not recognising adb connection

### ISSUE THREAD

**Issue by Thewisem** [mirfatif/PermissionManagerX#17]
When I try to change permission of an app using adb, it is saying privelege extension required even though adb is ticked.
Device: Samsung Galaxy Tab A
Version: SM P555

**Comment by mirfatif** [comment]
Please recheck. This should not happen if ADB is working correctly. Clear app data or reinstall the app and check again. Note any error messages (toasts). If the problem persists you need to get a detailed log (from About screen) and share with us.
You can also join Telegram support group for a quick coordination.

**Comment by Thewisem** [comment]
![Screenshot_20210728-135757](https://user-images.githubusercontent.com/74511929/127312148-167d1c8f-6e65-4fb7-b8c7-b5bfcd56baed.jpg)
![Screenshot_20210728-135528](https://user-images.githubusercontent.com/74511929/127312152-08b2686b-cda3-41ac-b918-9fd234626337.jpg)
![Screenshot_20210728-135816](https://user-images.githubusercontent.com/74511929/127312155-26ffbaff-8088-46cc-bc2a-a084e37b0295.jpg)
![Screenshot_20210728-075011](https://user-images.githubusercontent.com/74511929/127312157-5f54ecf2-688c-49f1-934a-60ac9b898666.jpg)
[PermissionManagerX_28-Jul-21_13-58-25.log](https://github.com/mirfatif/PermissionManagerX/files/6892481/PermissionManagerX_28-Jul-21_13-58-25.log)

**Comment by Thewisem** [comment]
Here

**Comment by Thewisem** [comment]
Sorry for the delayed response

**Comment by mirfatif** [comment]
ADB is not fully working on your device. It succeeds on initial check (so "ADB Shell" checkbox is ticked) but fails on subsequent tries when the actual work is to be done:
```
...
07-28 13:58:35.587 24212 24512 D Utils   : checkAdb: connecting to ADB succeeded
...
07-28 13:59:05.718 24212 24227 E PrivDaemonHandler: startDaemon: ... ADB connection timed out
...
07-28 13:59:35.780 24212 24227 E PrivDaemonHandler: startDaemon: ... ADB connection timed out
...
07-28 13:59:43.969 24212 24617 D Utils   : checkAdb: connecting to ADB succeeded
...
07-28 14:00:14.010 24212 24233 E PrivDaemonHandler: startDaemon: ... ADB connection timed out
...
07-28 14:00:44.041 24212 24233 E PrivDaemonHandler: startDaemon: ... ADB connection timed out
...
```
You can try from a PC to confirm if multiple concurrent connections to your device over Wireless ADB work.

**Comment by Thewisem** [comment]
Hmmm there isn't an option for wireless adb on android 7

**Comment by Thewisem** [comment]
But if you give a command you can command to use wireless adb by connecting to desktop

**Comment by Thewisem** [comment]
I gave it app ops permission

**Comment by mirfatif** [comment]
Here is a brief guide: [How to use PMX with ADB?](https://t.me/PermissionManagerX/456)

**Comment by Thewisem** [comment]
This allows access to adb

**Comment by Thewisem** [comment]
Which I already gave

**Comment by Thewisem** [comment]
If I didn't it wouldn't tick itself

**Comment by mirfatif** [comment]
You said that there isn't an option for wireless ADB on Android 7. So I provided the step by step guide how you can try from a PC to confirm if multiple concurrent connections to your device over Wireless ADB work or not.

But actually it's clear from the log that only first connection over Wireless ADB works. I'm sorry but we don't have a solution to this at the moment. It's a limitation of your device. It's the first case of its nature so far. If the problem arises frequently or if we get a physical device with the same problem, may be we can workaround it somehow. But it's not possible at the moment. Apologies.

**Comment by mirfatif** [comment]
[Using PMX with ADB](https://mirfatif.github.io/PermissionManagerX/help/help#adb_help)
