### ISSUE TITLE
Alternate option to pay/donate

### ISSUE THREAD

**Issue by sugarcane29** [mirfatif/PermissionManagerX#20]
I'd like to pay for the app/donate to the work.
However, I don't do any transactions of the play store.
Could you set up a paypal/buy me a coffee link.

Thanks.

**Comment by mirfatif** [comment]
Sorry I don't have PayPal, only Payoneer. Here is BMC: https://www.buymeacoffee.com/mirfatif
Thank you for the support. But Play Store version offers extra features which I would like you to use. Drop me an email or message on Telegram to get Play Store redeem code if you can use.
