### ISSUE TITLE
FR: Add Intent to start daemon over ADB

### ISSUE THREAD

**Issue by qwerty12** [mirfatif/PermissionManagerX#21]
Very useful application, thanks. 

I was wondering if an Intent can be added to have Permission Manager X start its daemon using ADB to avoid needing to bring up PMX's user interface.

(Background: on my unrooted Android device, I use Tasker and Termux to start Shizuku and ADB on port 5555 etc. automatically at boot. To be able to use the Permission Watcher features after every phone restart without needing to think about starting it manually, it'd be great if I could use `am` in a script instead of having to tap PMX's notification.)

Thanks.

**Comment by qwerty12** [comment]
> So you want PMX to receive an Intent to trigger ADB connection and
restart Watcher. Right?

Exactly.

My phone isn't rooted so I have Tasker/Termux connect to ADB using the
built in wireless debugging, and then use that session to run `adb tcpip`
which is, I think, the only way to get "traditional" ADB Wi-Fi running on
non-rooted phones. The problem is this is slow to do, so everything is long
started by this point. If there were an Intent I could broadcast with `am`
after running `adb tcpip` to have PMX's daemon running, it would allow me
to have that part automated, thanks.

**Comment by mirfatif** [comment]
> My phone isn't rooted so I have Tasker/Termux connect to ADB using the built in wireless debugging

By "built in wireless debugging" do you mean the [Wireless debugging feature available on Android 11+](https://mirfatif.github.io/PermissionManagerX/help/help.html#adb_help_11)? But adding pairing code and port already requires user interaction.

**Comment by qwerty12** [comment]
Yes.

Once paired (and with the "Disable adb authorisation timeout" developer
option turned on just to make sure the pairing isn't forgotten after some
time), you can pretty much have wireless debugging turned on without user
interaction (mostly).

Tasker with the Tasker Settings addon (an addon intentionally written to
target a lower SDK version so it can do this) can set the Global setting
`adb_wifi_enabled` to 1. Android will popup the dialog asking if you
authorise the action on the current Wi-Fi network; the Tasker AutoInput
plugin taps yes for me. When wireless debugging starts, it outputs the
random port it's using to the logcat. Tasker can read the log and extract
the port number, which gets passed to a shell script in Termux, which uses
the port number with an `adb` binary there.

**Comment by mirfatif** [comment]
Got it. I don't think many people will find this useful but adding to ToDo list.

**Comment by mirfatif** [comment]
Added in [v1.12-beta1](https://t.me/PermissionManagerX/3429):
```
am startservice -n com.mirfatif.permissionmanagerx/.fwk.AdbConnectSvcM --ei "com.mirfatif.pmx.extra.ADB_PORT" 5555
```

[Help](https://mirfatif.github.io/PermissionManagerX/help/en/#adb_connect_svc)

**Comment by qwerty12** [comment]
Thank you very much for fulfilling this request. I got around to trying the command in ADB and did, somehow, manage to get the service to start - I got errors on my first few goes, something like "the app is in the background" and `am` refused to start the service. I think I had to turn on "appear on top" for Termux to allow it to reliably start programs. I don't know if this would help here with `am` refusing to start PM's service, but if so, could the same permission be added to PM, please?

**Comment by mirfatif** [comment]
Did you try with `am start-foreground-service`?

**Comment by qwerty12** [comment]
I can't seem to get the same error to occur again; if it does, I'll keep your tip in mind. Thank you very much.
