### ISSUE TITLE
setting AppOps mode failed

### ISSUE THREAD

**Issue by xandro0777** [mirfatif/PermissionManagerX#22]
Hi, getting this popup every time when I want to change some permission. Did I do something wrong or is it simply so that my system doesn't allow any changes? I found the About/Privileges menu, at which entry should I look?

It is an Android 11 device and I have enabled it using just the ```adb tcpip 5555```command, not the more complicated procedure listed for Android 11.

TIA

**Comment by mirfatif** [comment]
There are multiple possible reasons why it's failing. We need logcat to figure our the root cause.

**Comment by xandro0777** [comment]
Looking at the logs, there is
```
 E PrivDaemon: com.mirfatif.privtasks.hiddenapis.HiddenAPIsException: java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
```

also see 
```
 W System.err: java.lang.NoSuchMethodError: No static method asInterface(Landroid/os/IBinder;)Landroid/permission/IPermissionManager; in class Landroid/permission/IPermissionManager$Stub; or its super classes (declaration of 'android.permission.IPermissionManager$Stub' appears in /system/framework/framework.jar!classes2.dex)
```
```
 E PrivDaemon: com.mirfatif.privtasks.hiddenapis.HiddenAPIsException: java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
```

Let me know if you need other info.

**Comment by mirfatif** [comment]
> Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.

> uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.

That's the unfortunate reality of crippled ADB privileges explained [here](https://mirfatif.github.io/PermissionManagerX/help/help#adb_help) in the start note. Sorry but we are quite helpless here. All I can suggest is to change the ROM.

**Comment by xandro0777** [comment]
Eureka!

There is apparently a setting in the developper options called "disable permission monitoring". If it is enabled everything appears to work - even things like settings editor that is unrelated to permissions :)

Please add this to the README, seems to work across many devices.

**Comment by mirfatif** [comment]
Good catch. I'll add. Kindly mention ROM. Some OEMs like Xiaomi and Oppo add extra security layers to USB debugging. This isn't part of AOSP.

**Comment by xandro0777** [comment]
It seems to be manyl Realme and Oppo, Xiaomi has something similar.

**Comment by mirfatif** [comment]
I meant what's your ROM. But anyway I'll add a general note. Thanks.

**Comment by aitemoure1979** [comment]
Ti diamo il benvenuto negli appunti di Gboard, in cui verrà salvato il
testo copiato.

في الثلاثاء، 25 يناير، 2022 19:40 xandro0777 ***@***.***> كتب:
