### ISSUE TITLE
[Feature Request] Automatic recovery

### ISSUE THREAD

**Issue by NSTAdventure** [mirfatif/PermissionManagerX#23]
problem:
starting from android 10 
App ops may reverted by system to default state 
this can causing problem other developer called rikka apps say android ecosystem is deeply hurt by them

solution:
automatic recovery Permission eXtended should able to keep app ops after being changed hy user by keep monitoring app ops state prevent system to revert it
and this can be done using ADB over TCP mode

**Comment by NSTAdventure** [comment]
> It's already covered in [Permission References](https://mirfatif.github.io/PermissionManagerX/help/help.html#perm_ref), [Permission Watcher](https://mirfatif.github.io/PermissionManagerX/help/help.html#perm_watcher) and [Scheduled Checker](https://mirfatif.github.io/PermissionManagerX/help/help.html#scheduled_checker). Suggestions are welcome on how we can improve this.

reading those guide I'm may still missing something do those option are prevent "ignore" setting from being reset by system?

**Comment by mirfatif** [comment]
> do those option are prevent "ignore" setting from being reset by system?

There is no way to prevent the operating system from changing AppOp modes. Permission Watcher and Schedule Checker help you restore your desired mode that you set as the Reference value.
 
Templates is an upcoming feature, but not very actively worked on at the moment.

We do not plan to use AccessibilityService due to its limitations and Play Store policy issues.

**Comment by aitemoure1979** [comment]
Tocca una clip per incollarla nella casella di testo.

في السبت، 5 فبراير، 2022 07:12 Irfan Latif ***@***.***> كتب:

**Comment by aitemoure1979** [comment]
💸 per il resto della fattura relativa alla pratica in questo caso non
fosse 5

في الخميس، 3 فبراير، 2022 09:16 NeverLand ***@***.***> كتب:
