### ISSUE TITLE
suggestion of a new feature [root access is required]

### ISSUE THREAD

**Issue by cpuuntery** [mirfatif/PermissionManagerX#25]
While you can control plenty of permission using Appops. But there are permissions you cannot control using Appops like [android.permission.INTERNET]
but according to this [post](https://android.stackexchange.com/a/217522) you can control other permissions using the file [runtime-permissions.xml]
the file path in android 6 to 9 is
`/data/system/users/<User_ID>/runtime-permissions.xml`
but in android 12
`/data/misc_de/0/apexdata/com.android.permission/runtime-permissions.xml`

For example, you can change

```
<shared-user name="com.termux">
    <item name="android.permission.READ_EXTERNAL_STORAGE" granted="true" flags="0" />
    <item name="android.permission.WRITE_EXTERNAL_STORAGE" granted="true" flags="0" />
    <item name="android.permission.INTERNET" granted="true" flags="0" />
</shared-user>
```
  
  
```
<shared-user name="com.termux">
    <item name="android.permission.READ_EXTERNAL_STORAGE" granted="true" flags="0" />
    <item name="android.permission.WRITE_EXTERNAL_STORAGE" granted="true" flags="0" />
    <item name="android.permission.INTERNET" granted="false" flags="0" />
</shared-user>
```

And android support parsing XML files. And I know I can edit the file manually, but the XML file has too many lines and the copy and paste after the edit is a hassle and a chore for me. I would appreciate it very much if this app will **automate** that process from me.

**Comment by mirfatif** [comment]
I'm sorry but parsing XML and editing files is no way a functionality of PMX.
The post you have linked is written by me. And as per my experience with Android permissions, trying to change app permissions by editing system files is not a reliable approach. But if it's unavoidable, editing it manually using a text editor is the best approach.
