### ISSUE TITLE
Batch operations on permissions

### ISSUE THREAD

**Issue by proggaliu** [mirfatif/PermissionManagerX#27]
When in permissions screen for an application it would be very useful to be able to set all permissions to a state in a batch. For example I usually set all permissions to "Deny" except a few which are nessecary for function.
Instead of manually have to go thru the whole list and set deny, it would be great to have an option to set all permissions to deny, then manually allow needed permissions.

**Comment by mirfatif** [comment]
Profiles is an planned feature. Though not actively worked on at the moment.

**Comment by mirfatif** [comment]
Pro feature: **Batch Operations / Profiles** is available in [v1.22-beta1](https://t.me/mirfatifApps/157).
