### ISSUE TITLE
close

### ISSUE THREAD

**Issue by Ahplla** [mirfatif/PermissionManagerX#30]

**Comment by mirfatif** [comment]
What are "additional permissions filters"? Please name exactly as in the app. What would "add permission not listed" option do?

**Comment by Ahplla** [comment]
There are some permissions that are not present to force always display in "Show extra AppOps, never excluded".  And other permissions are unique by the ROM vendor.  I have to edit an app, the manifest to add, it would be much simpler if it were possible for users to add custom permissions to the "Show extra AppOps, never excluded" list

**Comment by Ahplla** [comment]
Just some samples:

INTERACT_ACROSS_USERS
MANAGE_USERS
INTERACT_ACROSS_USERS_FULL
com.miui.securitycore.permission.XSPACE_DUAL

**Comment by mirfatif** [comment]
`INTERACT_ACROSS_USERS`, `MANAGE_USERS` and `INTERACT_ACROSS_USERS_FULL` are manifest permissions. While "Show extra AppOps, never excluded" is applicable to AppOp permissions. Manifest permissions cannot be applied to an app until they are not requested in the app's manifest file.

Please check [What are manifest permissions and AppOps?](https://mirfatif.github.io/IAnswers/android_appop_manifest_permissions)
