### ISSUE TITLE
Background permission dont work sometimes

### ISSUE THREAD

**Issue by Cyberdr3am** [mirfatif/PermissionManagerX#31]
Hello and thank you for your application. When I block the automatic start of an application and prohibit its operation in the background it very often happens that it still arrives at this launch in the background even if I have refused.

I tested many applications and some continue to launch in the background. I have to kill them manually but later they will still relaunch.
Can you explain to me why?
Thanks

**Comment by mirfatif** [comment]
Please check:

- [How to prevent Android apps from starting on device boot?](https://mirfatif.github.io/IAnswers/prevent_android_apps_start_on_boot)
- [Why do apps run in background on Android?](https://mirfatif.github.io/IAnswers/why_android_apps_run_in_background)
- [How to stop background apps on Android?](https://mirfatif.github.io/IAnswers/stop_background_apps_in_android)

Let me know if you have further queries.

**Comment by Cyberdr3am** [comment]
Thank you for your reply.
I would like to know how to disable the services of an application with adb.
I'm not root so I can't use apps like Disable Service.
I thought your app could allow me to disable some things with adb but I think it doesn't.
Can you tell me if any of your application or if there is a way to do it with adb.
Thank you for your answer

**Comment by mirfatif** [comment]
Using PMX you can disable apps but not their components, which a service is. Disabling or blocking app components is not possible without root.

**Comment by Cyberdr3am** [comment]
Alright thanks for your help. I will buy your apps to thank you and see what I can do with it without root.
