### ISSUE TITLE
allow critical changes is enabled but half of permissions are still greyed out

### ISSUE THREAD

**Issue by chiron853** [mirfatif/PermissionManagerX#33]
i cant change any permissions on some system apps even if i disable them and some permissions in user apps

**Comment by mirfatif** [comment]
Can you name a few such permissions?
Not all permissions are changeable. Did you see [Why can't I change XYZ permission?](https://mirfatif.github.io/PermissionManagerX/help/en/#faq15)

**Comment by chiron853** [comment]
but on android system all permissions are greyed out like post notifications

**Comment by mirfatif** [comment]
Android System (package name: `android`) is the Android framework i.e. the core operating system. Changing its permissions is like shooting in the foot. Your device will certainly be bricked. So is the case with some other core framework apps / processes.
If you don't trust your framework, and you want to deny its permissions, you should certainly stop using it and install another reliable ROM. Changing its permissions is not practically possible.

**Comment by chiron853** [comment]
can i make a modified apk of android system with changed permissions and copy that to system folder

**Comment by mirfatif** [comment]
A ROM developer can answer better.
