### ISSUE TITLE
Could you add a miui-like permission: Get Info about installed apps?

### ISSUE THREAD

**Issue by sunday123** [mirfatif/PermissionManagerX#34]
Could you add a miui-like permission: Get Info about installed apps?
This means that the user has denied this permission in xxApp, and xxApp can only view the system app, but cannot view the ordinary app.

Personally, I think this permission is important.

![miui permissions](https://user-images.githubusercontent.com/9637770/231626328-674fb42c-851b-45fa-8e1e-0b7fa93f526e.jpg)

I don't know if this permission is the same as the android.permission.QUERY_ALL_PACKAGES in the system, I looked at the protectionLevel of the android.permission.QUERY_ALL_PACKAGES is normal.

I found QUERY_ALL_PACKAGES permission setting on your software(v.1.16), so I set the QUERY_ALL_PACKAGES to deny. I found that it didn't work., and xxAPP was able to view all apps.

![v.1.16](https://user-images.githubusercontent.com/9637770/233651709-8c9da8a2-2fd5-4791-8fca-199a028a3f37.png)

**Comment by mirfatif** [comment]
> Could you add a miui-like permission: Get Info about installed apps?

We cannot add or remove permissions. PMX only shows a list of permissions already available on your device.

> I don't know if this permission is the same as the `android.permission.QUERY_ALL_PACKAGES`.

Protection level of `android.permission.QUERY_ALL_PACKAGES` is normal. So it is always granted and cannot be changed.

And the `QUERY_ALL_PACKAGES` AppOp allows to query all apps on device, regardless of the state of `android.permission.QUERY_ALL_PACKAGES`. So setting the former to `Deny` won't prevent the app from viewing all apps if the later is granted.

MIUI is a closed source operating system. We only have access to AOSP source code. So we do not have any way to find out what "Get Info about installed apps" permission actually does under the hood. If it's a[ manifest or AppOp permission](https://mirfatif.github.io/IAnswers/android_appop_manifest_permissions) (changeable or not), it should already be in the list of permissions.

**Comment by sunday123** [comment]
thx
