### ISSUE TITLE
Wireless Debugging fails

### ISSUE THREAD

**Issue by pflanzenandi** [mirfatif/PermissionManagerX#36]
Hello, I tried it a couple times, but PMX always gives back 'Pairing failed'.
Connecting via WI-FI ADB worked on e.g. Shizuke, so this can't be the problem. 

Can I give needed permissions also via USB debugging, as a work around?

Android 13
GrapheneOS
version 1.20

<img src="https://github.com/mirfatif/PermissionManagerX/assets/60046516/10580ed5-bad1-4638-a227-5f966fcbae99" width=40%>

**Comment by mirfatif** [comment]
Can you please share the logcat?

**Comment by mirfatif** [comment]
> PMX always gives back 'Pairing failed'

Can you please share the logcat?

> Can I give needed permissions also via USB debugging, as a work around?

Yes. Please see [Using PMX with ADB](https://mirfatif.github.io/PermissionManagerX/help/en/#adb_help) for a complete guide.
