### ISSUE TITLE
The extra AppOps list is not restored from backup

### ISSUE THREAD

**Issue by F-i-f** [mirfatif/PermissionManagerX#37]
PMX version 1.30-ps-pro (Google Play).

Steps to reproduce:
1. Install PMX Pro
2. Go to Hamburger menu > Exclusion Filters > Extra AppOps list
3. Add an AppOpp to the list (eg. WAKE_LOCK)
4. Export backup
5. Restore backup

I'd expect the Extra AppOps list to contain WAKE_LOCK.
However after the restore, the Extra AppOps list is reawt to it's default.

**Comment by mirfatif** [comment]
Fixed in [v1.21](https://github.com/mirfatif/PermissionManagerX/releases/tag/v1.21)
