### ISSUE TITLE
root: Files not extracted or not accessible

### ISSUE THREAD

**Issue by kolAflash** [mirfatif/PermissionManagerX#38]
After giving root permissions via Magisk I'm getting the popup message:
Files not extracted or not accessible

logcat:
System.err: DaemonHandler: extractDexFile(): Extracting failed: /storage/emulated/0/Android/d
ata/com.mirfatif.permissionmanagerx/files/com.mirfatif.privdaemon.pmx.dex

**Comment by Frydzyslaw** [comment]
#

**Comment by mirfatif** [comment]
You must be using F-Droid version? The issue has been fixed. Please install the [latest version](https://github.com/mirfatif/PermissionManagerX/releases/latest).
