### ISSUE TITLE
Feature request: block sensors like Accelerometer, Gyroscope

### ISSUE THREAD

**Issue by yiranshaxiao** [mirfatif/PermissionManagerX#40]
Thanks for awesome app. Will this app provider such feature like block Accelerometer sensors ?

**Comment by mirfatif** [comment]
Android allows unrestricted access to [motion sensors](https://developer.android.com/develop/sensors-and-location/sensors/sensors_motion). There's no permission to control it.

**Comment by pongfcnkl** [comment]
appops supports ignoring sensor permissions (Android 10 and above)
https://github.com/RikkaApps/App-Ops-issue-tracker/releases
