### ISSUE TITLE
Lack of permissions

### ISSUE THREAD

**Issue by AlxMxlA** [mirfatif/PermissionManagerX#43]
Many applications that go to Internet, your application (the latest version as well as) does not see any permits to work with the network.
Android14.
Of course, I get a warning that the phone firmware is not supported. But still.

Can this problem somehow solve this problem?

**Comment by mirfatif** [comment]
PXM is a permission manager, not a network firewall. Please see [How can I change INTERNET permission?](https://mirfatif.github.io/PermissionManagerX/help/en/#faq16).
