### ISSUE TITLE
Permission Change

### ISSUE THREAD

**Issue by SyCoREAPER** [mirfatif/PermissionManagerX#44]
I'm sure you would have added it if it was possible but why can ' Android.permission.RECEIVE_BOOT_COMPLETED ' not be changed?

I have a few apps that run at boot for unknown reasons, don't have an option to turn it on or off and can't find any apps that will stop them. I'm assuming this flag is what's telling the apps they should launch at boot. 
This assumption is based on that they don't relaunch automatically with 'RUN_IN_BACKGROUND' and 'RUN_ANY_INBACKGROUND' set to DENY

If this permission can't be changed (without ROOT), any interest in making a 'Boot App Manager' 🤪

**Comment by mirfatif** [comment]
See [Why can't I change XYZ permission?](https://mirfatif.github.io/PermissionManagerX/help/en/#faq15) and [How to prevent Android apps from starting on device boot?](https://mirfatif.github.io/IAnswers/prevent_android_apps_start_on_boot).
