### ISSUE TITLE
Support secondary profiles (multi-user devices)

### ISSUE THREAD

**Issue by maltfield** [mirfatif/PermissionManagerX#45]
This is a feature request to be able to execute PermissionManagerX as non-device-owner accounts.

### Problem

For security reasons, I mostly just use non-owner accounts on my Android device -- different profiles for different use-cases (security through compartimentalization).

I installed PermissionManagerX on one of my non-owner profiles, and I get the following error message

```
Permission Manager X can run only in the primary user account / device owner profile
```

I logged-in as the primary owner and installed PermissionManagerX. It opened, but the problem with this is that I need to check the permissions of the apps installed in the secondary user's profile. They aren't visible in the primary account's install of PermissionManagerX

### Solution

Please let me open PermissionManagerX inside non-device-owner profiles.

**Comment by maltfield** [comment]
See also https://github.com/mirfatif/PermissionManagerX/issues/4

^ This suggests to install it in the secondary profile, but obviously that doesn't work (per error in OP)

**Comment by mirfatif** [comment]
> I need to check the permissions of the apps installed in the secondary user's profile. They aren't visible in the primary account's install of PermissionManagerX

Please see [How to use the app in work profile / multi-user environment?](https://mirfatif.github.io/PermissionManagerX/help/en/#faq22)

> Please let me open PermissionManagerX inside non-device-owner profiles.

[ADB cannot read external storage of secondary users](https://android.stackexchange.com/a/221534/218526) which is required on non-rooted devices. Also there are issues getting apps/permissions info if the app is not running in primary profile. So we are not considering this.

**Comment by maltfield** [comment]
Thanks. Maybe you can update the error message to indicate that multi-user environment *is* supported, but only in the pro version?
