### ISSUE TITLE
ADB stopped working on Fire TV devices

### ISSUE THREAD

**Issue by webepg** [mirfatif/PermissionManagerX#46]
Hi,

since the latest update your stopped working on Fire TV Devices:

https://www.aftvnews.com/amazon-blocks-long-running-fire-tv-capability-breaking-popular-apps-with-no-warning-and-giving-developers-the-runaround/

Are you working on a workaround?

**Comment by mirfatif** [comment]
Root it, if possible. No other way, unfortunately.
