### ISSUE TITLE
Permission watcher functionality misbehaving in Pro version when targeting an app in Secondary profile (daemon as system) or outright misses an unfavorable permission change (if daemon as root)

### ISSUE THREAD

**Issue by Aleximal** [mirfatif/PermissionManagerX#47]
PMX: pro version, most recent, with trial key
Android 14

Target app: MoodSMS

Permissions targeted: call log, phone state, place calls, read device ID (all set to grant on platform level or MoodSMS won't start , but set to ignore at appops level

Sometimes the abovelisted appOpp permissions change on their own to "default/accept) which is a known behavior

NB : MoodSMS is running in Secondary user (!)

So I enabled permission watcher and made all the needed changes 

If daemon runs as root then permission change is missed and MoosSMS regains some unwanted permissions (and starts annoying notification on every phone call) 

If daemon runs as system the permission watcher seemingly manages to restore MoodSMS permissions to the state I want but periodically crashes with log: 
```
=================================
Version: v1.24-pro
SDK: 34
Build: user
Device: redfin
Manufacturer: Google
Model: Pixel 5
Product: redfin
=================================
Root: true
ADB: false
UID: 0
Context: u:r:magisk:s0
Time: 11-Apr-24 12:53:04
Component: Daemon
Log ID: 03599caa-204c-46e6-aa5b-60212a77cc67
=================================
java.lang.AbstractMethodError: abstract method "void android.permission.IOnPermissionsChangeListener.onPermissionsChanged(int, java.lang.String)"
	at android.permission.IOnPermissionsChangeListener$Stub.onTransact(IOnPermissionsChangeListener.java:89)
	at android.os.Binder.execTransactInternal(Binder.java:1501)
	at android.os.Binder.execTransact(Binder.java:1440)

=================================
Root: true
ADB: false
UID: 1000
Context: u:r:magisk:s0
Time: 11-Apr-24 13:06:51
Component: Daemon
Log ID: d67c9300-8db9-417f-9581-b6feae64a682
=================================
java.lang.AbstractMethodError: abstract method "void android.permission.IOnPermissionsChangeListener.onPermissionsChanged(int, java.lang.String)"
	at android.permission.IOnPermissionsChangeListener$Stub.onTransact(IOnPermissionsChangeListener.java:89)
	at android.os.Binder.execTransactInternal(Binder.java:1501)
	at android.os.Binder.execTransact(Binder.java:1440)
```

**Comment by mirfatif** [comment]
> NB : MoodSMS is running in Secondary user (!)
> 
> So I enabled permission watcher and made all the needed changes
> 
> If daemon runs as root then permission change is missed and MoosSMS regains some unwanted permissions (and starts annoying notification on every phone call)

This is a known behavior / bug as stated [here](https://mirfatif.github.io/PermissionManagerX/help/en/#perm_watcher):

> On some devices Permission Watcher may not work reliably for apps in the secondary user / profile. Using it in combination with Scheduled Checker is recommended.

---

> If daemon runs as system the permission watcher seemingly manages to restore MoodSMS permissions to the state I want but periodically crashes with log:

PMX is only tested on Android versions up to 13 as stated in the app description on Play Store and GitHub. We are working on fixing the issues with Android 14.
