### ISSUE TITLE
Add a non root version.

### ISSUE THREAD

**Issue by Pranab009** [mirfatif/PermissionManagerX#5]
Please add a non root version.
Or make it also for non rooted phones.
Almost 80% phones are non rooted.
Please.. please... please  work on it.

**Comment by mirfatif** [comment]
There **is** non-root option. Use ADB.

I wish the app could work without root, without ADB. But the limitation is at OS level. Normal user apps aren't that privileged to make changes to other apps and OS. And with every new Android release restrictions are getting bigger.

**Comment by Pranab009** [comment]
Without adb or root it can't work poperly.
Please make it's non root version that runs using accessibility permission.
And it can remove main permissions like storage, camera, contact, dialer, microphone etc.

**Comment by mirfatif** [comment]
Please see https://github.com/mirfatif/PermissionManagerX/issues/8#issuecomment-791044253
