### ISSUE TITLE
App always loses root permission

### ISSUE THREAD

**Issue by HarriBuh** [mirfatif/PermissionManagerX#50]
Since 1.25, the app will lose its root permission regularly, already after ~ 1 minute after closing it.
I then will always have to re-grant it inside the app (Magisk always logs it as "permission granted" btw.)

I have the "auto-stop daemon" option enabled, if this was important.

Google Pixel 7
Android 14
Magisk 27.0
App version 1.25-pro

**Comment by mirfatif** [comment]
Thanks for reporting.
Start log service from About -> Collect Logs. Then wait until the root is lost. Stop logging. Share the file.
