### ISSUE TITLE
global/specific preset for all installed apps

### ISSUE THREAD

**Issue by justinandoutdude** [mirfatif/PermissionManagerX#6]
Magnificent app. Thank you very much.

I just want to suggest adding an option for a preset (or pre setting a profile) of every appops element so that it could be implemented globally or to specific sets of apps.

Exemple: when you long press an app, along the already existing popup menu you get a 'select app' option, then the app gets highlighted, and on the topbar you get the option to select a pre existing profile you've already created in the setting menu with custom appops strings to be implemented. You could also select multiple apps and apply another profile through the same process.

**Comment by mirfatif** [comment]
Pro feature: **Batch Operations / Profiles** is available in [v1.22-beta1](https://t.me/mirfatifApps/157).
