### ISSUE TITLE
Auto revoke permissions when an app is closed

### ISSUE THREAD

**Issue by Hx2-code** [mirfatif/PermissionManagerX#7]
It would be great if permissions granted to an app can be automatically revoked when the app is not in use like in the app  [Bouncer](https://play.google.com/store/apps/details?id=com.samruston.permission) but using adb.

**Comment by mirfatif** [comment]
How we'd be keeping track of when an app enters and leaves foreground state without running as an Accessibility Service? Also it's not a good idea to revoke permissions of system apps in particular without user explicitly making any such changes. Device may get into a bootloop.

A very close solution is the _Scheduled Checks_ feature (available in Play Store version). Set a desired reference state (revoked) for a manifest permission or (Deny / Ignore for) an AppOp. So PMX performs the check at set frequency and verifies the current permission states against the ref states. And if found different (e.g. granted or Allow), it displays a warning notification. And so the users can take action the way they want.

**Comment by Hx2-code** [comment]
I did not mean by system apps. I was talking only about user installed apps.
Also you can use accessibility permission to track app running in the foreground.

**Comment by mirfatif** [comment]
https://mirfatif.github.io/PermissionManagerX/help/help.html#faq32
