### ISSUE TITLE
Add an option to instead give fake data 

### ISSUE THREAD

**Issue by Victor239** [mirfatif/PermissionManagerX#9]
XPrivacy was an Xposed module with a similar featureset to PMX, but when it was rewritten as [XPrivacyLua](https://github.com/M66B/XPrivacyLua) they instead swapped to feeding apps fake data, because revoking permissions often causes apps to crash or malfunction. 

It would be great to be great to see PMX have the same functionality. Xposed these days is too much of a security vulnerability for me to use but the root requirement of PMX suits my needs fine.

**Comment by mirfatif** [comment]
Thanks for the suggestion.

How do you think we can feed fake data to apps without modifying Android framework? And how can we have a better mod than Xposed which is not a security vulnerability (even root is)?

PMX is not targeted to be a framework mod. It provides a convenient access to some privileged APIs which normal apps cannot use. It's not hacking Android's standard functionality by any means. Most of the tasks PMX performs can also be performed from commandline. But giving fake data to apps is not possible from commandline. You need to hook into Android's internal APIs by replacing Android's libraries with your own hacked ones.

**Comment by Morrigan-Ship** [comment]
ReOpen this issue
this is important
fake respone for all Permissions ALL
